openapi: 3.0.3
info:
  title: SenseVoice Speech Recognition API
  description: 基于SenseVoice的语音识别服务API
  version: 1.0.0
  contact:
    name: SenseVoice API Team
    url: https://github.com/HG-ha/SenseVoice-Api

servers:
  - url: http://localhost:9880
    description: 本地SenseVoice服务器
  - url: https://your-sensevoice-domain.com
    description: 生产环境SenseVoice服务器

paths:
  /asr:
    post:
      summary: 语音识别
      description: 将音频文件转换为文字，基于SenseVoice模型
      operationId: speechToText
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: 音频文件 (支持 wav, mp3, flac, m4a 等格式)
                language:
                  type: string
                  description: 识别语言
                  default: auto
                  enum:
                    - auto
                    - zh
                    - en
                    - ja
                    - ko
                    - yue
                output_format:
                  type: string
                  description: 输出格式
                  default: text
                  enum:
                    - text
                    - json
              required:
                - audio
      responses:
        '200':
          description: 识别成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                    description: 状态码，0表示成功
                  message:
                    type: string
                    example: "success"
                    description: 状态信息
                  data:
                    type: object
                    properties:
                      text:
                        type: string
                        description: 识别出的文字内容
                        example: "你好，这是一段测试语音"
                      language:
                        type: string
                        description: 检测到的语言
                        example: "zh"
                      duration:
                        type: number
                        format: float
                        description: 音频时长（秒）
                        example: 3.2
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: 文件过大
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '415':
          description: 不支持的音频格式
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#   /health:
#     get:
#       summary: 健康检查
#       description: 检查SenseVoice服务状态
#       operationId: healthCheck
#       responses:
#         '200':
#           description: 服务正常
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   status:
#                     type: string
#                     example: "healthy"
#                   version:
#                     type: string
#                     example: "1.0.0"
#                   model:
#                     type: string
#                     example: "SenseVoice"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: 错误代码
          example: 400
        message:
          type: string
          description: 错误信息
          example: "音频文件格式不支持"
        data:
          type: object
          nullable: true
          description: 错误详细信息
      required:
        - code
        - message

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

# security:
#   - ApiKeyAuth: []